CREATE TABLE `teams` (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT
);
CREATE TABLE `roles` (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT,
	`description`	TEXT,
	`team_id`	INTEGER NOT NULL,
	FOREIGN KEY(`team_id`) REFERENCES teams (_id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE `role_combinations` (
	`id_role1`	INTEGER NOT NULL,
	`id_role2`	INTEGER NOT NULL,
	PRIMARY KEY(id_role1,id_role2),
	FOREIGN KEY(`id_role1`) REFERENCES roles (_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(`id_role2`) REFERENCES roles (_id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE `sets` (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`count`	INTEGER,
	`parent`	INTEGER DEFAULT -1
);
CREATE TABLE `set_nogo_roles` (
	`id_set`	INTEGER NOT NULL,
	`id_role`	INTEGER NOT NULL,
	PRIMARY KEY(id_set,id_role),
	FOREIGN KEY(`id_set`) REFERENCES sets (_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(`id_role`) REFERENCES roles (_id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE `set_roles` (
	`id_set`	INTEGER NOT NULL,
	`id_role`	INTEGER NOT NULL,
	PRIMARY KEY(id_set,id_role),
	FOREIGN KEY(`id_set`) REFERENCES sets (_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(`id_role`) REFERENCES roles (_id) ON UPDATE CASCADE ON DELETE CASCADE
);